authapp/urls.py
from authapp.apps import AuthappConfig
from django.urls import path
from authapp.views import MyLoginView, RegisterView, MyLogoutView, EditView

app_name = AuthappConfig.name

urlpatterns = [
    path('login/', MyLoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('logout/', MyLogoutView.as_view(), name='logout'),
    path('edit/', EditView.as_view(), name='edit'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('', RedirectView.as_view(url='mainapp/')),
    path('authapp/', include('authapp.urls', namespace='authapp')),
    path('mainapp/', include('mainapp.urls', namespace='mainapp')),
    path('social_auth/', include('social_django.urls', namespace='social')),

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _
from mainapp.models import NULLABLE


class User(AbstractUser):
    email = models.EmailField(verbose_name=_('email'), blank=True, unique=True)
    age = models.PositiveSmallIntegerField(verbose_name=_('age'), **NULLABLE)
    avatar = models.ImageField(
        verbose_name=_('avatar'), upload_to='users', **NULLABLE)

    class Meta:
        verbose_name = 'пользователь'
        verbose_name_plural = 'пользователи'

    def __str__(self) -> str:
        return f'{self.pk} | {self.username}'

authapp/forms.py
from typing import Any, Optional, Dict
from dataclasses import fields
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.core.exceptions import ValidationError


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = get_user_model()
        fields = (
            'username',
            'email',
            'first_name',
            'last_name',
            'age',
            'avatar',
        )
    
    def clean_age(self) -> Optional[Dict[str, Any]]:
        age = self.cleaned_data.get('age')
        
        if age < 18:
            raise ValidationError('Вы слишком молоды')

        return age


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = get_user_model()
        fields = (
            
            'username',
            'email',
            'first_name',
            'last_name',
            'age',
            'avatar',
            
        )
    
    def clean_age(self) -> Optional[Dict[str, Any]]:
        age = self.cleaned_data.get('age')
        
        if age < 18:
            raise ValidationError('Вы слишком молоды')

        return age

authapp/views.py
from typing import Any, Optional
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import TemplateView, CreateView, UpdateView
from authapp.models import User
from authapp.forms import CustomUserCreationForm, CustomUserChangeForm
from django.contrib import messages
from django.contrib.auth.views import LoginView, LogoutView
from django.utils.translation import gettext_lazy as _


class MyLoginView(LoginView):
    template_name = 'authapp/login.html'
    extra_context = {
        'title': _('User login')
    }


class RegisterView(CreateView):
    model = User
    form_class = CustomUserCreationForm
    success_url: Optional[str] = reverse_lazy('authapp:login')


class MyLogoutView(LogoutView):
    pass


class EditView(UpdateView):
    model = User
    form_class = CustomUserChangeForm
    template_name: str = 'authapp/edit.html'

    def get_object(self, queryset=None):
        return self.request.user

    def get_success_url(self) -> str:
        return reverse_lazy('authapp:edit')
      

authapp/templates/authapp/base.html
{% load static i18n %}

<!doctype html>
<html lang="ru">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <!-- ChartJS -->
    <link rel="stylesheet" href="{% static 'css/Chart.min.css' %}">

    <!-- FontAwesome -->
    <link rel="stylesheet" href="{% static 'css/fontawesome.all.min.css' %}">

    <title>Welcome to GeekLab!</title>
</head>

<body>

  {% include 'includes/inc_messages.html' %}
    <div class="row justify-content-around align-items-center" style="height: 100vh; margin: 0px">
        <div class="text-center">
          <p>
            <a href="/"><img src="{% static 'img/logo.png' %}" alt=""></a>
          </p>
          <h3>{{ title }}</h3>
        {% block content %}
            content
        {% endblock content %}
        
          <h4> {% translate "Login via social" %} </h4>
          <p>
            <div class="btn-group btn-block" role="group">
              <a class="btn btn-primary" href="{% url 'social:begin' 'vk-oauth2' %}" role="button"><i class="fab fa-vk"></i></a>
              <a class="btn btn-primary" href="{% url 'social:begin' 'github' %}" role="button"><i class="fab fa-github"></i></a>
              <a class="btn btn-primary" href="{% url 'social:begin' 'yaru' %}" role="button"><i class="fab fa-yandex"></i></a>
            </div>
            <div class="btn-group btn-block">
              <div class="col p-0 border-right">
                  <form action="{% url 'set_language' %}" method="post">
                      {% csrf_token %}
                      <input name="language" type="hidden" value="ru">
                      <button type="submit" class="btn btn-link">🇷🇺</button>
                  </form>
              </div>
              <div class="col p-0">
                  <form action="{% url 'set_language' %}" method="post">
                      {% csrf_token %}
                      <input name="language" type="hidden" value="en">
                      <button type="submit" class="btn btn-link">🇬🇧</button>
                  </form>
              </div>
            </div>
          </p>

        </div>
    </div>
    <!-- JavaScript section -->
    <!-- Bootstrap -->
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <!-- ChartJs -->
    <script src="{% static 'js/Chart.min.js' %}"></script>

    <!-- FontAwesome -->
    <script src="{% static 'js/fontawesome.all.min.js' %}"></script>


</body>

</html>

authapp/templates/authapp/edit.html
{% extends 'mainapp/base.html' %} 
{% load crispy_forms_tags %} 
{% load static i18n %}
{% block content %}

<form
  method="post"
  class="col-6 m-auto pt-5 pb-9"
  enctype="multipart/form-data">

  {% csrf_token %}
  
  
  
  <img src="{% if user.avatar %} {{ user.avatar.url }} {% else %} {%static 'img/no_img.png'%} {% endif %}" class="d-block w-100" alt="">
  
  {{ form|crispy }}

  <button type="submit" class="btn btn-primary btn-block">
    {% translate "save" %}
  </button>
</form>

{% endblock content %} 

{% block js_script %}

<script>
  $(document).ready(function () {
  {% if messages %}
  // Toasts
  $(".toast").toast({ delay: 5000 });
  $(".toast").toast("show");
  {% endif %}
  });
</script>

{% endblock js_script %}

authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}

{% load static i18n %}

{% block content %}

    <form method="post">
      {% csrf_token %}
      <p>
        <input id="id_username" class="form-control" type="text" name="username" placeholder="{% translate "User name" %}"
          required="" autofocus="">
      </p>
      <p>
        <input id="id_password" class="form-control" type="password" name="password" placeholder="{% translate "password" %}" required="">
      </p>
      <p>
        <button type="submit" class="btn btn-primary btn-block">
          {% translate "Login" %}
        </button>
      </p>
    </form>
    <p>
      <div class="row justify-content-between">
        <div class="col">
          <a href="{% url 'authapp:register' %}">
            <small> {% translate "Registration" %} </small>
          </a>
        </div>
        <div class="col">
          <a href="#">
            <small> {% translate "Forgot your password?" %} </small>
          </a>
        </div>
      </div>
    </p>

{% endblock content %}

{% block js_script %}

<script>
  $(document).ready(function () {
  {% if messages %}
  // Toasts
  $(".toast").toast({ delay: 5000 });
  $(".toast").toast("show");
  {% endif %}
  });
</script>

{% endblock js_script %}

authapp/templates/authapp/user_form.html
{% extends 'authapp/base.html' %}
{% load crispy_forms_tags %} 
{% load static i18n %} 
{% block content %}

<form method="post" class="mt-2" enctype="multipart/form-data">

  {% csrf_token %}

  {{ form|crispy }}

  <p>  
    <button type="submit" class="btn btn-primary btn-block">
      {% translate "Registration" %}
    </button>
  </p>
</form>

<p>
  <div class="row justify-content-between">
    <div class="col">
      <a href="{% url 'authapp:login' %}">
        <small> {% translate "Login" %} </small>
      </a>
    </div>
    <div class="col">
      <a href="#">
        <small> {% translate "Forgot your password?" %} </small>
      </a>
    </div>
  </div>
</p>

{% endblock content %} 

{% block js_script %}

<script>
  $(document).ready(function () {
  {% if messages %}
  // Toasts
  $(".toast").toast({ delay: 5000 });
  $(".toast").toast("show");
  {% endif %}
  });
</script>

{% endblock js_script %}