authapp/urls.py
from authapp.apps import AuthappConfig
from django.urls import path
from authapp.views import MyLoginView, RegisterView, MyLogoutView, EditView

app_name = AuthappConfig.name

urlpatterns = [
    path('login/', MyLoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('logout/', MyLogoutView.as_view(), name='logout'),
    path('edit/', EditView.as_view(), name='edit'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('', RedirectView.as_view(url='mainapp/')),
    path('authapp/', include('authapp.urls', namespace='authapp')),
    path('mainapp/', include('mainapp.urls', namespace='mainapp')),
    path('social_auth/', include('social_django.urls', namespace='social')),

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
from mainapp import views
from django.views.decorators.cache import cache_page
from mainapp.apps import MainappConfig

app_name = MainappConfig.name

urlpatterns = [
    path('', views.MainView.as_view(), name='index'),
    path('contacts/', views.ContacntsView.as_view(), name='contacts'),
    path('doc_site/', views.DocsView.as_view(), name='docs'),
    path('login/', views.LoginView.as_view(), name='login'),

    # Courses
    path('courses/', cache_page(360)(views.CoursesView.as_view()), name='courses'),
    path('courses/<int:pk>/detail/', views.CourseDetailView.as_view(), name='courses_detail'),
    path('courses/feedback/', views.CourseFeedbackCreateView.as_view(), name='course_feedback'),

    # News
    path('news/', views.NewsView.as_view(), name='news'),
    path('news/<int:pk>/detail/', views.NewsDetailView.as_view(), name='news_detail'),
    path('news/<int:pk>/delete/', views.NewsDeleteView.as_view(), name='news_delete'),
    path('news/<int:pk>/update/', views.NewsUpdateView.as_view(), name='news_update'),
    path('news/create/', views.NewsCreateView.as_view(), name='news_create'),

    # Logs
    path('logs/', views.LogView.as_view(), name='logs_list'),
    path('logs/download/', views.LogDownloadView.as_view(), name='logs_download'),

    # other
    path('search/', views.SearchView.as_view(), name='search'),
  ]

mainapp/models.py
from django.db import models
from django.conf import settings

NULLABLE = {'blank': True, 'null': True}


class BaseModel(models.Model):
    created_at = models.DateTimeField(verbose_name='Дата создания',
                                      auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(verbose_name='Дата модификации',
                                      auto_now=True, editable=False)
    deleted = models.BooleanField(verbose_name='Запись удалена', default=False)

    def delete(self, *args, **kwargs):
        self.deleted = True
        self.save()

    class Meta:
        # '-' говорит об обратной сортировке
        ordering = ('-created_at',)
        # важный флаг для исключения дублирования
        abstract = True


class ObjectsManager(models.Manager):

    def get_queryset(self):
        return super().get_queryset().all()


class News(BaseModel):
    objects = ObjectsManager()

    title = models.CharField(verbose_name='Заголовок', max_length=255)
    preview = models.CharField(verbose_name='Описание', max_length=1000)
    body = models.TextField(verbose_name='Содержание')

    body_as_markdown = models.BooleanField(verbose_name='Тип MD',
                                           default=False)

    def __str__(self) -> str:
        return f'{self.pk} {self.title}'

    class Meta:
        verbose_name = 'новость'
        verbose_name_plural = 'новости'
        ordering = BaseModel.Meta.ordering


class Course(BaseModel):
    objects = ObjectsManager()

    name = models.CharField(verbose_name='Название', max_length=256)
    description = models.TextField(verbose_name='Описание', **NULLABLE)
    description_as_markdown = models.BooleanField(verbose_name='Тип MD',
                                                  default=False)
    cost = models.DecimalField(verbose_name='Стоимость',
                               max_digits=8, decimal_places=2, default=0)
    cover = models.FileField(verbose_name='Обложка',
                             max_length=25, default='no_image.svg')

    def __str__(self) -> str:
        return f'{self.pk} {self.name}'

    class Meta:
        verbose_name = 'курс'
        verbose_name_plural = 'курсы'


class Lesson(BaseModel):
    objects = ObjectsManager()

    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    num = models.PositiveIntegerField(verbose_name='Номер')
    title = models.CharField(verbose_name='Тема', max_length=256)
    description = models.TextField(verbose_name='Описание', **NULLABLE)
    description_as_markdown = models.BooleanField(
        verbose_name='Тип MD', default=False)

    def __str__(self) -> str:
        return f'{self.course.name} | {self.num} | {self.title}'

    class Meta:
        verbose_name = 'урок'
        verbose_name_plural = 'уроки'

        ordering = ('course', 'num')


class CoursesTeacher(BaseModel):

    courses = models.ManyToManyField(Course)
    name_first = models.CharField(verbose_name='Имя', max_length=128)
    name_second = models.CharField(verbose_name='Фамилия', max_length=128)
    day_birth = models.DateField(verbose_name='Дата рождения')

    def __str__(self) -> str:
        return f'{self.pk} | {self.name_second} {self.name_first}'


class CourseFeedback(BaseModel):
    RATING_FIVE = 5

    RATINGS = (
        (RATING_FIVE, '⭐⭐⭐⭐⭐'),
        (4, '⭐⭐⭐⭐'),
        (3, '⭐⭐⭐'),
        (2, '⭐⭐'),
        (1, '⭐'),
    )

    course = models.ForeignKey(
        Course, 
        verbose_name='Курс', 
        on_delete=models.CASCADE
    )

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, 
        verbose_name='Пользователь',
        on_delete=models.CASCADE, 
    )

    rating = models.SmallIntegerField(
        verbose_name='Рейтинг',
        choices=RATINGS,
        default=RATING_FIVE,
    )

    feedback = models.TextField(
        verbose_name='Отзыв', 
        default='Без отзыва',
    )

    class Meta:
        verbose_name = 'отзыв'
        verbose_name_plural = 'отзовы'

    def __str__(self) -> str:
        return f'Отзыв на {self.course} от {self.user}'

mainapp/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from mainapp.models import CourseFeedback


class CourseFeedbackForm(forms.ModelForm):

    class Meta:
        model = CourseFeedback
        fields = (
            'course',
            'user',
            'rating',
            'feedback',
        )

        widgets = {
            'course': forms.HiddenInput(),
            'user': forms.HiddenInput(),
            # 'rating': forms.RadioSelect(),
        }

    def __init__(self, *args, course=None, user=None, **kwargs):
        super().__init__(*args, **kwargs)
        if course and user:
            self.fields['course'].initial = course.pk
            self.fields['user'].initial = user.pk


class ContactsFeedbackForm(forms.Form):

    user_id = forms.IntegerField(widget=forms.HiddenInput)
    message_body = forms.CharField(
        widget=forms.Textarea,
        help_text=_('enter your message'),
        label=_('message'),
    )

    def __init__(self, *args, user=None, **kwargs):
        super().__init__(*args, **kwargs)
        if user:
            self.fields['user_id'].initial = user.pk

mainapp/views.py
from datetime import datetime
from urllib import request, response
from django.core.cache import cache
from django.conf import settings
from django.shortcuts import get_object_or_404, redirect, render
from django.http import FileResponse, HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, CreateView, UpdateView, DeleteView, DetailView, View
from mainapp.models import Course, Lesson, News, CoursesTeacher, CourseFeedback
from mainapp.forms import CourseFeedbackForm, ContactsFeedbackForm
from mainapp import tasks
from django.contrib.auth.mixins import PermissionRequiredMixin, UserPassesTestMixin
from django.template.loader import render_to_string


class MainView(TemplateView):
    template_name = 'mainapp/index.html'


class ContacntsView(TemplateView):
    template_name = 'mainapp/contacts.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['object_data'] = [
            {
                'city': 'Санкт‑Петербург',
                'phone': '+7-999-11-11111',
                'email': 'geeklab@spb.ru',
                'addr': 'территория Петропавловская крепость, 3Ж',
                'map': 'https://yandex.ru/map-widget/v1/-/CCUAZHcrhA',
            }, {
                'city': 'Казань',
                'phone': '+7-999-22-22222',
                'email': 'geeklab@kz.ru',
                'addr': 'территория Кремль, 11, Казань, Республика Татарстан, Россия',
                'map': 'https://yandex.ru/map-widget/v1/-/CCUAZHX3xB',
            }, {
                'city': 'Москва',
                'phone': '+7-999-33-33333',
                'email': 'geeklab@msk.ru',
                'addr': 'Красная площадь, 7, Москва, Россия',
                'map': 'https://yandex.ru/map-widget/v1/-/CCUAZHh9kD',
            },
        ]
        context_data['form'] = ContactsFeedbackForm(user=self.request.user)
        return context_data

    def post(self, *args, **kwargs):
        message_body = self.request.POST.get('message_body')
        message_from = self.request.user.pk if self.request.user.is_authenticated else None
        tasks.send_feedback_to_email.delay(message_body, message_from)

        return HttpResponseRedirect(reverse_lazy('mainapp:contacts'))


class CoursesView(ListView):
    template_name = 'mainapp/courses_list.html'
    model = Course


class CourseDetailView(TemplateView):
    template_name = 'mainapp/course_detail.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['course_object'] = get_object_or_404(
            Course, pk=self.kwargs.get('pk'))
        context_data['lessons'] = Lesson.objects.filter(
            course=context_data['course_object'])
        context_data['teachers'] = CoursesTeacher.objects.filter(
            courses=context_data['course_object'])

        feedback_list_key = f'course_feedback_{context_data["course_object"].pk}'

        cached_feedback_list = cache.get(feedback_list_key)

        if cached_feedback_list is None:
            context_data['feedback_list'] = CourseFeedback.objects.filter(
                course=context_data['course_object'])
            cache.set(feedback_list_key,
                      context_data['feedback_list'], timeout=300)
        else:
            context_data['feedback_list'] = cached_feedback_list

        if self.request.user.is_authenticated:
            if not CourseFeedback.objects.filter(course=context_data['course_object'], user=self.request.user).count():
                context_data['feedback_form'] = CourseFeedbackForm(
                    course=context_data['course_object'],
                    user=self.request.user
                )
        from django.core.paginator import Paginator
        paginator = Paginator(context_data['feedback_list'], 5)
        paginator.page(1)

        return context_data


class CourseFeedbackCreateView(CreateView):
    model = CourseFeedback
    form_class = CourseFeedbackForm

    def form_valid(self, form):
        self.object = form.save()
        rendered_template = render_to_string(
            "includes/feedback_card.html",
            context={'item': self.object}
        )
        return JsonResponse({'card': rendered_template})


class DocsView(TemplateView):
    template_name = 'mainapp/doc_site.html'


class LoginView(TemplateView):
    template_name = 'mainapp/login.html'


class NewsView(ListView):
    model = News
    paginate_by = 2

    def get_queryset(self):
        return super().get_queryset().filter(deleted=False)


class NewsDetailView(DetailView):
    model = News

    # def get_context_data(self, **kwargs):
    #     context_data = super().get_context_data(**kwargs)
    #     context_data['course_object'] = get_object_or_404(Course, pk=self.kwargs['pk'])

    #     return context_data


class NewsCreateView(PermissionRequiredMixin, CreateView):
    model = News
    fields = '__all__'
    success_url = reverse_lazy('mainapp:news')
    permission_required = ('mainapp:news_create',)


class NewsUpdateView(PermissionRequiredMixin, UpdateView):
    model = News
    fields = '__all__'
    success_url = reverse_lazy('mainapp:news')
    permission_required = ('mainapp:change_news', )


class NewsDeleteView(PermissionRequiredMixin, DeleteView):
    model = News
    success_url = reverse_lazy('mainapp:news')
    permission_required = ('mainapp:delete_news', )


class SearchView(View):
    def get(self, request):
        response = request.GET['param'].replace(' ', '+')
        return redirect(f'https://yandex.ru/search/?text={response}&lr=11219')


class LogView(UserPassesTestMixin, TemplateView):
    template_name = 'mainapp/logs.html'

    def test_func(self):
        return self.request.user.is_superuser

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        log_lines = []

        with open(settings.BASE_DIR / 'log/main_log.log') as file:
            for i, line in enumerate(file):
                if i == 1000:
                    break
                log_lines.insert(0, line)

            context_data['logs'] = log_lines

        return context_data


class LogDownloadView(UserPassesTestMixin, View):

    def test_func(self):
        return self.request.user.is_superuser

    def get(self, *args, **kwargs):
        return FileResponse(open(settings.LOG_FILE, "rb"))

mainapp/templates/includes/feedback_card.html
<div class="card mb-3">
  <div class="card-body">
    <h5 class="card-title">{{ item.get_rating_display }}</h5>
    <h6 class="card-subtitle mb-2 text-muted">{{ item.user }}</h6>
    <p class="card-text">{{ item.feedback }}</p>
  </div>
</div>

mainapp/templates/includes/inc_main_menu.html
{% load static i18n %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="{% url 'mainapp:index' %}">
            <img src="{%static 'img/logo.png'%}" alt="">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item ">
                    <a class="nav-link 
                        {% if request.resolver_match.view_name == 'mainapp:news' %}
                            active
                        {% endif %}" 
                        href="{% url 'mainapp:news' %}">
                        {% translate "News" %}
                    </a>
                </li>
                <li class="nav-item ">
                    <a class="nav-link 
                        {% if request.resolver_match.view_name == 'mainapp:courses' %}
                            active
                        {% endif %}" 
                        href="{% url 'mainapp:courses' %}">
                        {% translate "Courses" %}
                    </a>
                </li>

                <li class="nav-item ">
                    <a class="nav-link
                        {% if request.resolver_match.view_name == 'mainapp:contacts' %}
                            active
                        {% endif %}" 
                        href="{% url 'mainapp:contacts' %}">
                        {% translate "Contacts" %}
                    </a>
                </li>

                {% if user.is_authenticated %}

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="ddProfile" role="button" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                       {% translate "Profile" %}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="ddProfile">
                        <a class="dropdown-item" href="{% url 'authapp:edit' %}">
                            {% translate "Edit profile" %}
                        </a>
                        <a class="dropdown-item" href="#">
                            {% translate "My courses" %}
                        </a>

                        {% if user.is_staff %}
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'admin:index' %}">
                                {% translate "Moderation" %}
                            </a>
                        {% endif %}

                        {% if user.is_superuser %}
                            <a class="dropdown-item" href="{% url 'admin:index' %}">
                                {% translate "Administrative section" %}
                            </a>
                            <a class="dropdown-item" href="{% url 'mainapp:logs_list' %}">
                                {% translate "Logs" %}
                            </a>
                        {% endif %}
                        
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'authapp:logout' %}">
                            {% translate "Logout" %}
                        </a>
                    </div>

                </li>

                <li class="nav-item ">
                    <a class="nav-link"
                    href="{% url 'authapp:edit' %}">{{ user.first_name|default:user.username }}</a>
                </li>

                {% else %}

                <li class="nav-item ">
                    <a class="nav-link"
                        href="{% url 'authapp:login' %}">
                        {% translate "Login" %}
                    </a>
                </li>

                {% endif %}

            </ul>
            <div class="row justyfy-content-end m-0">
                <div class="col p-0 border-right">
                    <form action="{% url 'set_language' %}" method="post">
                        {% csrf_token %}
                        <input name="language" type="hidden" value="ru">
                        <button type="submit" class="btn btn-link">🇷🇺</button>
                    </form>
                </div>
                <div>
                    <form action="{% url 'set_language' %}" method="post">
                        {% csrf_token %}
                        <input name="language" type="hidden" value="en">
                        <button type="submit" class="btn btn-link">🇬🇧</button>
                    </form>
                </div>
            </div>
            
        </div>
    </div>
</nav>

mainapp/templates/includes/main_menu.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="{% url 'mainapp:index' %}">
            <img src="/static/img/logo.png" alt="">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item ">
                    <a class="nav-link 
                    {% if request.resolver_match.view_name == 'mainapp:news' %}
                        active
                    {% endif %}" 
                    href="{% url 'mainapp:news' %}">Новости</a>
                </li>
                <li class="nav-item ">
                    <a class="nav-link 
                    {% if request.resolver_match.view_name == 'mainapp:courses' %}
                        active
                    {% endif %}" 
                    href="{% url 'mainapp:courses' %}">Курсы</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="ddProfile" role="button" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        Профиль
                    </a>
                    <div class="dropdown-menu" aria-labelledby="ddProfile">
                        <a class="dropdown-item" href="#">Редактировать профиль</a>
                        <a class="dropdown-item" href="#">Мои курсы</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Модерация</a>
                        <a class="dropdown-item" href="#">Административный раздел</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Выход</a>
                    </div>
                </li>
                <li class="nav-item ">
                    <a class="nav-link
                    {% if request.resolver_match.view_name == 'mainapp:contacts' %}
                        active
                    {% endif %}" 
                    href="{% url 'mainapp:contacts' %}">Контакты</a>
                </li>
            </ul>
            <span><a href="#">🇷🇺</a> <i class="fas fa-grip-lines-vertical"></i> <a href="#">🇬🇧</a></span>
        </div>
    </div>
</nav>